name: Nightly eBay Data Scraper

on:
  schedule:
    # Run at 3 AM UTC (late night/early morning US time)
    - cron: '0 3 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd server
          npm ci
          
      - name: Create service account file
        run: |
          cd server
          mkdir -p credentials
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > credentials/service-account.json
        
      - name: Run scraper for popular cards
        run: |
          cd server
          node scripts/nightly-scrape.js
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./server/credentials/service-account.json 